---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: ${nameSpace}
data:
  clusterType: "macbook"
  mgmtClusterName: ww-paulc-macbook
  dnsSuffix: kubernetes.docker.internal
  clusterIP: 10.105.127.50
  GitHubOrg: ww-gitops
  GitHubRepo: paulcarlton-ww-macbook
  awsAccountId: ac-749339757188
  prefixName: ww-paulc
  awsRegion: eu-west-1
  awsTagCreator: paul.carlton@weave.works
  awsTagCustomer: weaveworks-cx
  awsTagProjectGid: "20276"
  userEmail: paul.carlton@weave.works
  vault_url: https://vault.kubernetes.docker.internal
  commitUser: paulcarlton-ww
