apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.dev.wkp.weave.works/releases/charts-v3
  secretRef:
    name: weave-gitops-enterprise-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 1m0s
  timeout: 5m
  values:
    enableExplorer: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      tls:
        - secretName: wge-tls
          hosts:
            - wge.${dnsSuffix}
      hosts:
        - host: wge.${dnsSuffix}
          paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
    config:
      git:
        type: github
        hostname: github.com
      capi:
        repositoryURL: https://github.com/${GitHubOrg}/${GitHubRepo}
      oidc:
        enabled: true
        issuerURL: https://dex.${dnsSuffix}
        redirectURL: https://wge.${dnsSuffix}/oauth2/callback
        clientCredentialsSecret: wge-oidc-auth
    policy-agent:
      enabled: true
      excludeNamespaces:
        - flux-system
        - kube-system
      config:
        clusterId: macbook
    tls:
      enabled: false
    enablePipelines: true
    enableTerraformUI: true
    global:
      capiEnabled: false
  postRenderers:
    - kustomize:
        patches:
        - target:
            kind: Deployment
            name: weave-gitops-enterprise-mccp-cluster-service
          patch: |-
            - op: add
              path: /spec/template/spec/hostAliases
              value:
                - ip: ${clusterIP}
                  hostnames:
                  - "dex.${dnsSuffix}"
                  - "wge.${dnsSuffix}"

            - op: add
              path: /spec/template/spec/volumes/-
              value:
                name: local-ca
                configMap:
                  name: local-ca

            - op: add
              path: /spec/template/spec/containers/0/volumeMounts/-
              value:
                name: local-ca
                mountPath: /etc/ssl/certs/local-ca.pem
                subPath: CA.cer
                readOnly: false
        images:
          - name: ghcr.io/weaveworks/gitopssets-controller
            newName: pcarlton/gitopssets-controller
            newTag: 1.0.0