clusters: 
- name: ${wge_cluster_name}
  cluster:
    certificate-authority-data: ${cert}
    server: ${endpoint}
contexts: 
- name: ${wge_cluster_name}
  context:
    cluster: ${wge_cluster_name}
    user: wge
users: 
- name: wge
  user:
    token: ${token}