---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitopssets-role
  namespace: ${nameSpace}
rules:
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitopssets-role-binding
  namespace: ${nameSpace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitopssets-role
subjects:
- kind: ServiceAccount
  name: gitopssets-kustomization
  namespace: ${nameSpace}