---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: ${nameSpace}
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200 # https://vault.${hostName} 
      path: ${nameSpace}
      version: v2
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "vault"
          key: "vault-token"