# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: dex-config
#   namespace: dex
# spec:
#   refreshInterval: 10m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: vault
#   target:
#     name: dex-config
#     creationPolicy: Owner
#   data:
#     - secretKey: config.yaml
#       remoteRef:
#         key: dex-config

# apiVersion: v1
# data:
#   client-id: "1b05d9f8957b6d90987b"
#   client-secret: "14ed847f9cdc710d38be43210affe2099e72b828"
# kind: Secret
# metadata:
#   name: github-client
#   namespace: dex
# ---
# apiVersion: v1
# data:
#   "config.yaml": "ImNvbm5lY3RvcnMiOgotICJjb25maWciOgogICAgImJhc2VVUkwiOiAiaHR0cHM6Ly9naXRodWIuY29tIgogICAgImNsaWVudElEIjogImJlYzNkMTg5M2YxZDkxNWU3YTRmIgogICAgImNsaWVudFNlY3JldCI6ICI5NjU1Y2MzMzBjZmRkMGFhYmM3MDI1N2I5NWNiNGY5YzlmOTMxZDUzIgogICAgImdyb3VwcyI6CiAgICAtICJ3dy1naXRvcHMiCiAgICAicmVkaXJlY3RVUkkiOiAiaHR0cHM6Ly9kZXgua3ViZXJuZXRlcy5kb2NrZXIuaW50ZXJuYWwvY2FsbGJhY2siCiAgImlkIjogImdpdGh1YiIKICAibmFtZSI6ICJHaXRIdWIiCiAgInR5cGUiOiAiZ2l0aHViIgoiaXNzdWVyIjogImh0dHBzOi8vZGV4Lmt1YmVybmV0ZXMuZG9ja2VyLmludGVybmFsIgoib2F1dGgyIjoKICAic2tpcEFwcHJvdmFsU2NyZWVuIjogdHJ1ZQoic3RhdGljQ2xpZW50cyI6Ci0gImlkIjogIndnZSIKICAibmFtZSI6ICJXZWF2ZSBHaXRvcHMgRW50ZXJwcmlzZSIKICAicmVkaXJlY3RVUklzIjoKICAtICJodHRwczovL3dnZS5rdWJlcm5ldGVzLmRvY2tlci5pbnRlcm5hbC9vYXV0aDIvY2FsbGJhY2siCiAgInNlY3JldCI6ICJBaUFJbXVYS2hvSTVBcHZLV0Y5ODh0eGpaKzZyRzNTN282WDVFbiIKLSAiaWQiOiAidmF1bHQiCiAgIm5hbWUiOiAiVmF1bHQiCiAgInJlZGlyZWN0VVJJcyI6CiAgLSAiaHR0cHM6Ly92YXVsdC5rdWJlcm5ldGVzLmRvY2tlci5pbnRlcm5hbC91aS92YXVsdC9hdXRoL29pZGMvb2lkYy9jYWxsYmFjayIKICAtICJodHRwOi8vbG9jYWxob3N0OjgyNTAvb2lkYy9jYWxsYmFjayIKICAic2VjcmV0IjogImFiY2RlZmdoIgoic3RvcmFnZSI6CiAgInR5cGUiOiAibWVtb3J5Igoid2ViIjoKICAiaHR0cCI6ICIwLjAuMC4wOjU1NTYi"
# kind: Secret
# metadata:
#   name: dex-config
#   namespace: dex