---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-creds
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: aws-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aws-creds
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-write-token
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: github-repo-write-token
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: github-repo-write-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: receiver-token
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: receiver-token
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: receiver-token
